CREATE DATABASE Inscon1;
USE Inscon1;

CREATE TABLE utilisateurs(
    idUser INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Nom VARCHAR(100) NOT NULL,
    Pseudo VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL
);