CREATE DATABASE InsCon1;
USE InsCon1;

CREATE TABLE utilisateurs(
    idUser INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Nom VARCHAR(100) NOT NULL,
    Pseudo VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MotDePasse VARCHAR(100) NOT NULL
);
